# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: John Sturgeon
subtitle: Thoughts and musings while working on projects.
email: john.sturgeon@me.com
description: >- # this means to ignore newlines until "baseurl:"
  Retired software engineer, contributor to open source projects when I can.
  Working on way too many projects and hobbies, and making notes here along the way.
url: "https://johnsturgeon.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  johnsturgeon
repository: johnsturgeon/blog

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true


author:
  name: "John Sturgeon"
  avatar: "/assets/images/bio-photo.png"
  bio: "Retired software engineer, contributor to open source projects when I can.
  Working on way too many projects and hobbies, and making notes here along the way." # Note: Markdown is allowed
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://pdx.social/@johnsturgeon"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/johnsturgeon"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/johnsturgeon"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
