authors:
  johnsturgeon:
    name: John Sturgeon
    description: Retired software engineer.
    avatar: assets/images/bio-photo.png
    slug: https://mastodon.social/@johnsturgeon
    url: https://mastodon.social/@johnsturgeon