authors:
  johnsturgeon:
    name: John Sturgeon
    description: Retired software engineer.
    avatar: assets/images/bio-photo.png
    slug: https://github.com/johnsturgeon
    url: https://github.com/johnsturgeon